### ISSUE TITLE
Parallel tests

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#23] opened 2015-02-04 09:00 UTC
_From @pawal on January 30, 2015 9:55_

This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

In order to increase the performance of Zonemaster, we talked about running tests in parallell rather than in sequence.

_Copied from original issue: dotse/zonemaster#322_

**Comment by pawal** [comment] 2015-02-04 09:00
_From @cdybedahl on January 30, 2015 9:57_

If we rewrite the whole thing in Erlang this would just fall out naturally :-)

**Comment by cdybedahl** [comment] 2015-02-09 14:28
The more I think about this, the more problems I have with it.

* Currently tests work against objects that look up things in DNS lazily, that is only when they're actually needed. Combining this behavior with several test modules running at the same time is going to be quite interesting.
* How is the progress thing in the web GUI going to deal with the answer to the question "Which test is running right now?" being "all of them"?
* Having the order the tests finish in be determined by the times foreign name servers take to respond is not all that compatible with producing predictable and reproducible test results.

**Comment by cdybedahl** [comment] 2015-03-24 06:58
Starting with version 0.73, Net::LDNS supports threading, removing one technical hurdle for this. All design issues still remain, though,

**Comment by pawal** [comment] 2015-03-24 09:34
So far it looks very good.

**Comment by cdybedahl** [comment] 2015-03-27 14:21
There is now a prototype threaded version in [my fork of the repo](https://github.com/cdybedahl/zonemaster-engine/tree/threaded). As far as possible, it runs every test case in a separate thread. The tests blow up like whoa, the new behavior is not documented at all and I've seen at least one coredump while testing it, but it does basically work. If it's installed, the CLI will use it.

The main difference to know about if you want to try using it as a library is that the logger callback is running in its own thread, so getting data out of it is not straightforward.

**Comment by cdybedahl** [comment] 2015-03-30 10:24
The coredump is found and will be fixed in Net::LDNS 0.75. Most of the test failures are because the tested domain no longer behaves as they did when the tests were written, or because of assumptions of serial-ness.

Running tests with zonemaster-cli on a bunch of more or less randomly chosen domains give varying timing results. For some domains, the threaded version takes up to 40% less time to finish. For other domains it takes 10-20% _more_ time to finish, compared to the unthreaded version.

**Comment by cdybedahl** [comment] 2015-03-31 15:06
Closing this one for now. There is enough of a prototype to evaluate if it's worth the effort to continue developing the threaded version, and the issue can be re-opened if needed.

**Closed by cdybedahl** 2015-03-31 15:06 UTC
Labels: enhancement, Prio Low, question
