### ISSUE TITLE
DNS Cookies

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#279] opened 2017-01-25 07:59 UTC
Request for DNSViz by Mark Andrews:

> Can DNSVis please send queries with DNS COOKIES enabled?                                                       
> That way all the servers that mishandle such queries will get                                                  
> flagged as being broken.                                                                                       

DNS Cookies was defined in [RFC7873](https://tools.ietf.org/html/rfc7873).

Very useful addition to Zonemaster as well.

**Comment by matsduf** [comment] 2017-01-25 10:02
This issue is a duplicate of an existing issue, https://github.com/dotse/zonemaster/issues/484

**Closed by matsduf** 2017-01-25 10:02 UTC
