### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#107] opened 2015-08-17 13:20 UTC
It happens sometimes I get output such as this from my zonemaster-collect code:

Thread 25 terminated abnormally: malformed UTF-8 character in JSON string, at character offset 8620 (before "\x{fffd}2002::/16","...") at (eval 587) line 161.

It comes from the zonemaster-engine, but I have not examined it closer, so I don't know the cause.

**Comment by vlevigneron** [comment] 2015-08-17 14:59
Patrik, I never met this case (but I don't often use json output), do
you have any idea if it happens with specific domain names ? What kind
of test could be done to reproduce this test case and catch that bug ?
I mean, how many domains do you use with zonemaster-collector, which
ones could I use to try to reproduce this issue ?

le 17 août, Patrik Wallström a ?crit :
> It happens sometimes I get output such as this from my zonemaster-collect code:
> 
> Thread 25 terminated abnormally: malformed UTF-8 character in JSON string, at character offset 8620 (before "\x{fffd}2002::/16","...") at (eval 587) line 161.
> 
> It comes from the zonemaster-engine, but I have not examined it closer, so I don't know the cause.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/107

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment] 2015-10-09 08:35
Closed it as of now we cannot reproduce this issue ..

**Closed by sandoche2k** 2015-10-09 08:35 UTC
Labels: bug
